apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-front
  labels:
    app: devops-front
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-front
  template:
    metadata:
      labels:
        app: devops-front
    spec:
      containers:
      - image: resincrt/devops-front:v1.0.6
        imagePullPolicy: Always
        name: devops-front
        ports:
        - containerPort: 80
          protocol: TCP